### PR TITLE
New icon tags

### PR DESCRIPTION
**Pull request by Galixte**
For this: https://github.com/Jalle19/xbmc-video-server/issues/181.

Those icons have the same height like those: https://github.com/bauruine/xbmc-video-server/commit/64e368f45a1abcc41bcf0e04a601f44f7ff9b43a.

I don't know which code we have to add.

### CODE REVIEW

**Comment by Jalle19** [comment]
Thanks, I'll add the necessary code changes. By the way, there are some new strings to translate if you're interested.

**Comment by Galixte** [comment]
Done, here: https://github.com/Jalle19/xbmc-video-server/pull/258.

**Comment by Jalle19** [comment]
Can you post some example file names that use these flags? I don't really have any CAM material in my library.

**Comment by Galixte** [comment]
The.Movie.CAM.MD.XviD-team.avi
The. Movie.WEBRip.AC3.x264-team.mkv
The.Movie.DVDSCR.LD.XviD-team.avi
…

**Comment by Galixte** [comment]
Thanks !

**Pull request merged**
